add limiting comments feature
shmcaffrey/step-portfolio pull request #13
Opened 2020-07-01 18:59 UTC by shmcaffrey

2020-07-01 21:27 UTC, robotsaurus requested changes

2020-07-01 21:27 UTC, robotsaurus commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    private String convertJsonUsingGson(ArrayList<String> comments) {
nit: looks like this is indented more than the others

2020-07-01 21:27 UTC, robotsaurus commented on portfolio/src/main/webapp/script.js
> +        console.log("deleting old comments");
this doesn't seem to be appropriate here

2020-07-01 21:27 UTC, robotsaurus commented on portfolio/src/main/webapp/index.html
> +          <!-- <button onclick="deleteAllComments()">Delete All Comments</button> -->
Is this meant to be commented out?

2020-07-01 22:53 UTC, snazzorama commented on portfolio/src/main/webapp/script.js
> +    fetch("/delete-data", {method: 'POST'}).then(document.getElementById("comment-contianer").innerText = "");
nit: "container" is misspelled

2020-07-01 23:52 UTC, shmcaffrey commented
ptal

2020-07-02 00:40 UTC, snazzorama approved these changes

2020-07-06 20:28 UTC, shmcaffrey commented
ptal

2020-07-07 17:13 UTC, robotsaurus approved these changes

2020-07-07 17:23 UTC, merged